/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-G1vOsZBTtig4zdDcULuiZQus8lu0h-1qljie4l3Bje93v-EKO--5H31xkjJdShJ4UzHeJ46uIB63CmVJuvA6lb8tigim0lLomcQrR0SW3rPxaHi5b4vrmB1B",
  "tt": "tt-1-FUJKdFK6aznd9iTHK4l9xgexwzwxfrG-otWR-iyhwqc=",
  "version": "2020-11-20"
}

export default ebconfig;